name: Build and Release MCPB Package

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to build (e.g., 1.0.0)'
        required: true
        default: '1.0.0'

jobs:
  build-mcpb:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install MCPB CLI
      run: |
        python -m pip install --upgrade pip
        pip install mcpb

    - name: Install Python dependencies
      run: |
        pip install -r requirements.txt

    - name: Validate MCPB package
      run: mcpb validate manifest.json

    - name: Build MCPB package
      run: |
        mkdir -p dist
        mcpb pack . dist/blender-mcp-${{ github.event.inputs.version || github.ref_name }}.mcpb

    - name: Verify package contents
      run: |
        mcpb info dist/*.mcpb
        mcpb unpack dist/*.mcpb temp_verify/
        ls -la temp_verify/

    - name: Upload MCPB artifact
      uses: actions/upload-artifact@v4
      with:
        name: blender-mcp-mcpb
        path: dist/*.mcpb

    - name: Create GitHub Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v2
      with:
        files: dist/*.mcpb
        generate_release_notes: true
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
