name: Release MCPB Package

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  release-mcpb:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')

    permissions:
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install MCPB CLI
      run: |
        python -m pip install --upgrade pip
        pip install mcpb

    - name: Install Python dependencies
      run: |
        pip install -r requirements.txt

    - name: Validate MCPB package
      run: mcpb validate manifest.json

    - name: Build MCPB package
      run: |
        mkdir -p dist
        mcpb pack . dist/blender-mcp-${{ github.ref_name }}.mcpb

    - name: Verify package contents
      run: |
        mcpb info dist/*.mcpb
        ls -lh dist/

    - name: Create checksums
      run: |
        cd dist
        sha256sum *.mcpb > CHECKSUMS.sha256
        cat CHECKSUMS.sha256

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          dist/*.mcpb
          dist/CHECKSUMS.sha256
        body: |
          ## Blender MCP Release ${{ github.ref_name }}

          **Complete Blender 3D automation MCP server with 48 tools across 19 categories**

          Professional Blender integration for Claude Desktop enabling natural language 3D workflows.

          ### Features
          - **48 specialized tools** across 19 categories
          - **Complete Blender Python API** integration
          - **Professional 3D workflows** automation
          - **FastMCP 2.12** compliant server
          - **Cross-platform** compatibility

          ### Installation
          Download the `.mcpb` file and add to your Claude Desktop configuration.

          ### Categories
          - Mesh Creation & Editing
          - Material & Texturing
          - Lighting & Rendering
          - Animation & Rigging
          - Physics & Simulation
          - Import/Export Operations
          - Scene Management
          - Camera Control
          - UV Mapping
          - Add-ons Management

          ### Verification
          Verify package integrity using the included `CHECKSUMS.sha256` file.
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
