name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9, "3.10", "3.11"]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .[dev]

    - name: Run unit tests (no Blender required)
      run: |
        python -m pytest tests/unit/ -v --cov=src/blender_mcp --cov-report=xml

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: false

  # Optional: Integration tests with Blender (only on main branch)
  integration-test:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    needs: test

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .[dev]

    - name: Install Blender (skip for now - complex setup)
      run: |
        # Blender installation on Ubuntu is complex, skip for CI
        # TODO: Set up proper Blender installation for integration tests
        echo "Skipping Blender installation - integration tests will be skipped"

    - name: Run integration tests (with Blender)
      run: |
        # Skip integration tests when Blender is not installed
        echo "Integration tests skipped - Blender not installed in CI"

    - name: Run performance tests (with Blender)
      run: |
        # Skip performance tests when Blender is not installed
        echo "Performance tests skipped - Blender not installed in CI"
